from tkinter import *
import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import test_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    test_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    test_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font9 = "-family {Segoe UI} -size 9 -weight bold -slant roman "  \
            "-underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("1357x844+281+69")
        top.title("Sensorsenasatie")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")
        self.var1 = StringVar()
        self.var2 = StringVar()
        self.var1.set(0)
        self.TFrame1 = ttk.Frame(top)
        self.TFrame1.place(relx=0.0, rely=0.0, relheight=0.053, relwidth=0.991)
        self.TFrame1.configure(relief='groove')
        self.TFrame1.configure(borderwidth="2")
        self.TFrame1.configure(relief='groove')
        self.TFrame1.configure(width=1325)

        self.TLabel1 = ttk.Label(self.TFrame1)
        self.TLabel1.place(relx=0.0, rely=0.222, height=24, width=86)
        self.TLabel1.configure(background="#d9d9d9")
        self.TLabel1.configure(foreground="#000000")
        self.TLabel1.configure(font=font9)
        self.TLabel1.configure(relief='flat')
        self.TLabel1.configure(text='''Handmatig:''')

        self.style.map('TRadiobutton',background=
            [('selected', _bgcolor), ('active', _ana2color)])
        self.TRadiobutton1 = ttk.Radiobutton(self.TFrame1)
        self.TRadiobutton1.place(relx=0.059, rely=0.222, relwidth=0.031
                , relheight=0.0, height=26)
        self.TRadiobutton1.configure(text='''Uit''', variable=self.var1, value=0)

        self.TRadiobutton2 = ttk.Radiobutton(self.TFrame1)
        self.TRadiobutton2.place(relx=0.097, rely=0.222, relwidth=0.036
                , relheight=0.0, height=26)
        self.TRadiobutton2.configure(text='''Aan''', variable=self.var1, value=1)

        self.TLabel2 = ttk.Label(self.TFrame1)
        self.TLabel2.place(relx=0.149, rely=0.222, height=24, width=107)
        self.TLabel2.configure(background="#d9d9d9")
        self.TLabel2.configure(foreground="#000000")
        self.TLabel2.configure(font=font9)
        self.TLabel2.configure(relief='flat')
        self.TLabel2.configure(text='''Alle schermen:''')

        self.TRadiobutton3 = ttk.Radiobutton(self.TFrame1)
        self.TRadiobutton3.place(relx=0.223, rely=0.222, relwidth=0.06
                , relheight=0.0, height=26)
        self.TRadiobutton3.configure(takefocus="")
        self.TRadiobutton3.configure(text='''Oprollen''', variable=self.var2, value=0)

        self.TRadiobutton4 = ttk.Radiobutton(self.TFrame1)
        self.TRadiobutton4.place(relx=0.283, rely=0.222, relwidth=0.059
                , relheight=0.0, height=26)
        self.TRadiobutton4.configure(takefocus="")
        self.TRadiobutton4.configure(text='''Uitrollen''', variable=self.var2, value=1)

        self.TProgressbar1 = ttk.Progressbar(self.TFrame1)
        self.TProgressbar1.place(relx=0.491, rely=0.222, relwidth=0.074
                , relheight=0.0, height=22)

        self.TLabel23 = ttk.Label(self.TFrame1)
        self.TLabel23.place(relx=0.394, rely=0.222, height=24, width=116)
        self.TLabel23.configure(background="#d9d9d9")
        self.TLabel23.configure(foreground="#000000")
        self.TLabel23.configure(font="TkDefaultFont")
        self.TLabel23.configure(relief='flat')
        self.TLabel23.configure(text='''Op- of uitgerold:''')

        self.Label1 = tk.Label(self.TFrame1)
        self.Label1.place(relx=0.476, rely=0.222, height=26, width=17)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''1:''')

        self.Label2 = tk.Label(self.TFrame1)
        self.Label2.place(relx=0.58, rely=0.222, height=26, width=17)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''2:''')

        self.Label3 = tk.Label(self.TFrame1)
        self.Label3.place(relx=0.684, rely=0.222, height=26, width=17)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''3:''')

        self.Label4 = tk.Label(self.TFrame1)
        self.Label4.place(relx=0.788, rely=0.222, height=26, width=17)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''4:''')

        self.Label5 = tk.Label(self.TFrame1)
        self.Label5.place(relx=0.892, rely=0.222, height=26, width=14)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''5:''')

        self.TProgressbar2 = ttk.Progressbar(self.TFrame1)
        self.TProgressbar2.place(relx=0.595, rely=0.222, relwidth=0.074
                , relheight=0.0, height=22)

        self.TProgressbar3 = ttk.Progressbar(self.TFrame1)
        self.TProgressbar3.place(relx=0.699, rely=0.222, relwidth=0.074
                , relheight=0.0, height=22)

        self.TProgressbar4 = ttk.Progressbar(self.TFrame1)
        self.TProgressbar4.place(relx=0.803, rely=0.222, relwidth=0.074
                , relheight=0.0, height=22)

        self.TProgressbar5 = ttk.Progressbar(self.TFrame1)
        self.TProgressbar5.place(relx=0.907, rely=0.222, relwidth=0.074
                , relheight=0.0, height=22)

        self.TFrame2 = ttk.Frame(top)
        self.TFrame2.place(relx=0.0, rely=0.047, relheight=0.19, relwidth=0.991)
        self.TFrame2.configure(relief='groove')
        self.TFrame2.configure(borderwidth="2")
        self.TFrame2.configure(relief='groove')
        self.TFrame2.configure(width=1325)

        self.TFrame7 = ttk.Frame(self.TFrame2)
        self.TFrame7.place(relx=0.004, rely=0.031, relheight=0.906
                , relwidth=0.227)
        self.TFrame7.configure(relief='groove')
        self.TFrame7.configure(borderwidth="2")
        self.TFrame7.configure(relief='groove')
        self.TFrame7.configure(width=305)

        self.TFrame12 = ttk.Frame(self.TFrame2)
        self.TFrame12.place(relx=0.242, rely=0.031, relheight=0.906
                , relwidth=0.16)
        self.TFrame12.configure(relief='groove')
        self.TFrame12.configure(borderwidth="2")
        self.TFrame12.configure(relief='groove')
        self.TFrame12.configure(width=215)

        self.TLabel3 = ttk.Label(self.TFrame2)
        self.TLabel3.place(relx=0.476, rely=0.063, height=24, width=95)
        self.TLabel3.configure(background="#d9d9d9")
        self.TLabel3.configure(foreground="#000000")
        self.TLabel3.configure(font=font9)
        self.TLabel3.configure(relief='flat')
        self.TLabel3.configure(text='''Diagrammen''')

        self.TLabel8 = ttk.Label(self.TFrame2)
        self.TLabel8.place(relx=0.431, rely=0.188, height=24, width=81)
        self.TLabel8.configure(background="#d9d9d9")
        self.TLabel8.configure(foreground="#000000")
        self.TLabel8.configure(font="TkDefaultFont")
        self.TLabel8.configure(relief='flat')
        self.TLabel8.configure(text='''Tempratuur''')

        self.TLabel9 = ttk.Label(self.TFrame2)
        self.TLabel9.place(relx=0.543, rely=0.188, height=24, width=35)
        self.TLabel9.configure(background="#d9d9d9")
        self.TLabel9.configure(foreground="#000000")
        self.TLabel9.configure(font="TkDefaultFont")
        self.TLabel9.configure(relief='flat')
        self.TLabel9.configure(text='''Licht''')

        self.TButton1 = ttk.Button(self.TFrame2)
        self.TButton1.place(relx=0.424, rely=0.375, height=30, width=98)
        self.TButton1.configure(takefocus="")
        self.TButton1.configure(text='''Lijndiagram''')

        self.TButton2 = ttk.Button(self.TFrame2)
        self.TButton2.place(relx=0.52, rely=0.375, height=30, width=98)
        self.TButton2.configure(takefocus="")
        self.TButton2.configure(text='''Lijndiagram''')

        self.TButton3 = ttk.Button(self.TFrame2)
        self.TButton3.place(relx=0.424, rely=0.688, height=30, width=100)
        self.TButton3.configure(takefocus="")
        self.TButton3.configure(text='''Staafdiagram''')

        self.TButton4 = ttk.Button(self.TFrame2)
        self.TButton4.place(relx=0.52, rely=0.688, height=30, width=100)
        self.TButton4.configure(takefocus="")
        self.TButton4.configure(text='''Staafdiagram''')

        self.TLabel18 = ttk.Label(self.TFrame2)
        self.TLabel18.place(relx=0.669, rely=0.063, height=24, width=114)
        self.TLabel18.configure(background="#d9d9d9")
        self.TLabel18.configure(foreground="#000000")
        self.TLabel18.configure(font=font9)
        self.TLabel18.configure(relief='flat')
        self.TLabel18.configure(text='''Op/uitrollen''')

        self.TButton21 = ttk.Button(self.TFrame2)
        self.TButton21.place(relx=0.974, rely=0.0, height=30, width=38)
        self.TButton21.configure(takefocus="")
        self.TButton21.configure(text='''X''')

        self.TButton26 = ttk.Button(self.TFrame2)
        self.TButton26.place(relx=0.669, rely=0.688, height=30, width=98)
        self.TButton26.configure(takefocus="")
        self.TButton26.configure(text='''Submit''')

        self.TLabel24 = ttk.Label(self.TFrame2)
        self.TLabel24.place(relx=0.84, rely=0.063, height=24, width=94)
        self.TLabel24.configure(background="#d9d9d9")
        self.TLabel24.configure(foreground="#000000")
        self.TLabel24.configure(font=font9)
        self.TLabel24.configure(relief='flat')
        self.TLabel24.configure(text='''Automatisch''')

        self.TLabel25 = ttk.Label(self.TFrame2)
        self.TLabel25.place(relx=0.81, rely=0.375, height=24, width=45)
        self.TLabel25.configure(background="#d9d9d9")
        self.TLabel25.configure(foreground="#000000")
        self.TLabel25.configure(font="TkDefaultFont")
        self.TLabel25.configure(relief='flat')
        self.TLabel25.configure(text='''Temp:''')

        self.TLabel26 = ttk.Label(self.TFrame2)
        self.TLabel26.place(relx=0.87, rely=0.375, height=24, width=38)
        self.TLabel26.configure(background="#d9d9d9")
        self.TLabel26.configure(foreground="#000000")
        self.TLabel26.configure(font="TkDefaultFont")
        self.TLabel26.configure(relief='flat')
        self.TLabel26.configure(text='''Licht:''')

        self.Entry1 = tk.Entry(self.TFrame2)
        self.Entry1.place(relx=0.84, rely=0.375,height=24, relwidth=0.019)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(selectforeground="black")

        self.Entry2 = tk.Entry(self.TFrame2)
        self.Entry2.place(relx=0.892, rely=0.375,height=24, relwidth=0.019)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(highlightbackground="#d9d9d9")
        self.Entry2.configure(highlightcolor="black")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(selectbackground="#c4c4c4")
        self.Entry2.configure(selectforeground="black")

        self.Scale1 = tk.Scale(self.TFrame2)
        self.Scale1.place(relx=0.684, rely=0.25, relwidth=0.074, relheight=0.0
                , height=47, bordermode='ignore')
        self.Scale1.configure(activebackground="#ececec")
        self.Scale1.configure(background="#d9d9d9")
        self.Scale1.configure(font="TkTextFont")
        self.Scale1.configure(foreground="#000000")
        self.Scale1.configure(highlightbackground="#d9d9d9")
        self.Scale1.configure(highlightcolor="black")
        self.Scale1.configure(orient="horizontal")
        self.Scale1.configure(troughcolor="#d9d9d9")

        self.TButton27 = ttk.Button(self.TFrame2)
        self.TButton27.place(relx=0.84, rely=0.688, height=30, width=98)
        self.TButton27.configure(takefocus="")
        self.TButton27.configure(text='''Submit''')

        self.TButton28 = ttk.Button(self.TFrame2)
        self.TButton28.place(relx=0.948, rely=0.0, height=30, width=38)
        self.TButton28.configure(takefocus="")
        self.TButton28.configure(text='''V''')

        self.TLabel47 = ttk.Label(self.TFrame2)
        self.TLabel47.place(relx=0.639, rely=0.375, height=24, width=67)
        self.TLabel47.configure(background="#d9d9d9")
        self.TLabel47.configure(foreground="#000000")
        self.TLabel47.configure(font="TkDefaultFont")
        self.TLabel47.configure(relief='flat')
        self.TLabel47.configure(wraplength="0")
        self.TLabel47.configure(takefocus="0")
        self.TLabel47.configure(text='''Rolstand:''')
        self.TLabel47.configure(width=0)

        self.TFrame3 = ttk.Frame(top)
        self.TFrame3.place(relx=0.0, rely=0.231, relheight=0.19, relwidth=0.991)
        self.TFrame3.configure(relief='groove')
        self.TFrame3.configure(borderwidth="2")
        self.TFrame3.configure(relief='groove')
        self.TFrame3.configure(width=1325)

        self.TFrame8 = ttk.Frame(self.TFrame3)
        self.TFrame8.place(relx=0.004, rely=0.031, relheight=0.906
                , relwidth=0.227)
        self.TFrame8.configure(relief='groove')
        self.TFrame8.configure(borderwidth="2")
        self.TFrame8.configure(relief='groove')
        self.TFrame8.configure(width=215)

        self.TFrame13 = ttk.Frame(self.TFrame3)
        self.TFrame13.place(relx=0.242, rely=0.031, relheight=0.906
                , relwidth=0.16)
        self.TFrame13.configure(relief='groove')
        self.TFrame13.configure(borderwidth="2")
        self.TFrame13.configure(relief='groove')
        self.TFrame13.configure(width=205)

        self.TLabel4 = ttk.Label(self.TFrame3)
        self.TLabel4.place(relx=0.476, rely=0.063, height=24, width=95)
        self.TLabel4.configure(background="#d9d9d9")
        self.TLabel4.configure(foreground="#000000")
        self.TLabel4.configure(font=font9)
        self.TLabel4.configure(relief='flat')
        self.TLabel4.configure(text='''Diagrammen''')

        self.TLabel10 = ttk.Label(self.TFrame3)
        self.TLabel10.place(relx=0.431, rely=0.188, height=24, width=81)
        self.TLabel10.configure(background="#d9d9d9")
        self.TLabel10.configure(foreground="#000000")
        self.TLabel10.configure(font="TkDefaultFont")
        self.TLabel10.configure(relief='flat')
        self.TLabel10.configure(text='''Tempratuur''')

        self.TLabel11 = ttk.Label(self.TFrame3)
        self.TLabel11.place(relx=0.543, rely=0.188, height=24, width=35)
        self.TLabel11.configure(background="#d9d9d9")
        self.TLabel11.configure(foreground="#000000")
        self.TLabel11.configure(font="TkDefaultFont")
        self.TLabel11.configure(relief='flat')
        self.TLabel11.configure(text='''Licht''')

        self.TButton5 = ttk.Button(self.TFrame3)
        self.TButton5.place(relx=0.424, rely=0.375, height=30, width=98)
        self.TButton5.configure(takefocus="")
        self.TButton5.configure(text='''Lijndiagram''')

        self.TButton6 = ttk.Button(self.TFrame3)
        self.TButton6.place(relx=0.424, rely=0.688, height=30, width=100)
        self.TButton6.configure(takefocus="")
        self.TButton6.configure(text='''Staafdiagram''')

        self.TButton7 = ttk.Button(self.TFrame3)
        self.TButton7.place(relx=0.52, rely=0.375, height=30, width=98)
        self.TButton7.configure(takefocus="")
        self.TButton7.configure(text='''Lijndiagram''')

        self.TButton8 = ttk.Button(self.TFrame3)
        self.TButton8.place(relx=0.52, rely=0.688, height=30, width=100)
        self.TButton8.configure(takefocus="")
        self.TButton8.configure(text='''Staafdiagram''')

        self.TLabel19 = ttk.Label(self.TFrame3)
        self.TLabel19.place(relx=0.669, rely=0.063, height=24, width=90)
        self.TLabel19.configure(background="#d9d9d9")
        self.TLabel19.configure(foreground="#000000")
        self.TLabel19.configure(font=font9)
        self.TLabel19.configure(relief='flat')
        self.TLabel19.configure(text='''Op/uitrollen''')

        self.TButton22 = ttk.Button(self.TFrame3)
        self.TButton22.place(relx=0.974, rely=0.0, height=30, width=38)
        self.TButton22.configure(takefocus="")
        self.TButton22.configure(text='''X''')

        self.TButton29 = ttk.Button(self.TFrame3)
        self.TButton29.place(relx=0.948, rely=0.0, height=30, width=38)
        self.TButton29.configure(takefocus="")
        self.TButton29.configure(text='''V''')

        self.TLabel27 = ttk.Label(self.TFrame3)
        self.TLabel27.place(relx=0.84, rely=0.063, height=24, width=94)
        self.TLabel27.configure(background="#d9d9d9")
        self.TLabel27.configure(foreground="#000000")
        self.TLabel27.configure(font=font9)
        self.TLabel27.configure(relief='flat')
        self.TLabel27.configure(takefocus="0")
        self.TLabel27.configure(text='''Automatisch''')

        self.TLabel28 = ttk.Label(self.TFrame3)
        self.TLabel28.place(relx=0.639, rely=0.375, height=24, width=67)
        self.TLabel28.configure(background="#d9d9d9")
        self.TLabel28.configure(foreground="#000000")
        self.TLabel28.configure(font="TkDefaultFont")
        self.TLabel28.configure(relief='flat')
        self.TLabel28.configure(wraplength="0")
        self.TLabel28.configure(takefocus="0")
        self.TLabel28.configure(text='''Rolstand:''')
        self.TLabel28.configure(width=0)

        self.TLabel30 = ttk.Label(self.TFrame3)
        self.TLabel30.place(relx=0.81, rely=0.375, height=24, width=45)
        self.TLabel30.configure(background="#d9d9d9")
        self.TLabel30.configure(foreground="#000000")
        self.TLabel30.configure(font="TkDefaultFont")
        self.TLabel30.configure(relief='flat')
        self.TLabel30.configure(takefocus="0")
        self.TLabel30.configure(text='''Temp:''')

        self.TLabel31 = ttk.Label(self.TFrame3)
        self.TLabel31.place(relx=0.87, rely=0.375, height=24, width=38)
        self.TLabel31.configure(background="#d9d9d9")
        self.TLabel31.configure(foreground="#000000")
        self.TLabel31.configure(font="TkDefaultFont")
        self.TLabel31.configure(relief='flat')
        self.TLabel31.configure(takefocus="0")
        self.TLabel31.configure(text='''Licht:''')

        self.Scale3 = tk.Scale(self.TFrame3)
        self.Scale3.place(relx=0.684, rely=0.25, relwidth=0.074, relheight=0.0
                , height=47, bordermode='ignore')
        self.Scale3.configure(activebackground="#ececec")
        self.Scale3.configure(background="#d9d9d9")
        self.Scale3.configure(font="TkTextFont")
        self.Scale3.configure(foreground="#000000")
        self.Scale3.configure(highlightbackground="#d9d9d9")
        self.Scale3.configure(highlightcolor="black")
        self.Scale3.configure(orient="horizontal")
        self.Scale3.configure(takefocus="0")
        self.Scale3.configure(troughcolor="#d9d9d9")

        self.Entry3 = tk.Entry(self.TFrame3)
        self.Entry3.place(relx=0.84, rely=0.375,height=24, relwidth=0.019)
        self.Entry3.configure(background="white")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font="TkFixedFont")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(highlightbackground="#d9d9d9")
        self.Entry3.configure(highlightcolor="black")
        self.Entry3.configure(insertbackground="black")
        self.Entry3.configure(selectbackground="#c4c4c4")
        self.Entry3.configure(selectforeground="black")
        self.Entry3.configure(takefocus="0")

        self.Entry4 = tk.Entry(self.TFrame3)
        self.Entry4.place(relx=0.892, rely=0.375,height=24, relwidth=0.019)
        self.Entry4.configure(background="white")
        self.Entry4.configure(disabledforeground="#a3a3a3")
        self.Entry4.configure(font="TkFixedFont")
        self.Entry4.configure(foreground="#000000")
        self.Entry4.configure(highlightbackground="#d9d9d9")
        self.Entry4.configure(highlightcolor="black")
        self.Entry4.configure(insertbackground="black")
        self.Entry4.configure(selectbackground="#c4c4c4")
        self.Entry4.configure(selectforeground="black")
        self.Entry4.configure(takefocus="0")

        self.TButton33 = ttk.Button(self.TFrame3)
        self.TButton33.place(relx=0.669, rely=0.688, height=30, width=98)
        self.TButton33.configure(takefocus="")
        self.TButton33.configure(text='''Submit''')

        self.TButton34 = ttk.Button(self.TFrame3)
        self.TButton34.place(relx=0.84, rely=0.688, height=30, width=98)
        self.TButton34.configure(takefocus="")
        self.TButton34.configure(text='''Submit''')

        self.TFrame4 = ttk.Frame(top)
        self.TFrame4.place(relx=0.0, rely=0.782, relheight=0.19, relwidth=0.991)
        self.TFrame4.configure(relief='groove')
        self.TFrame4.configure(borderwidth="2")
        self.TFrame4.configure(relief='groove')
        self.TFrame4.configure(width=1325)

        self.TFrame9 = ttk.Frame(self.TFrame4)
        self.TFrame9.place(relx=0.004, rely=0.063, relheight=0.906
                , relwidth=0.227)
        self.TFrame9.configure(relief='groove')
        self.TFrame9.configure(borderwidth="2")
        self.TFrame9.configure(relief='groove')
        self.TFrame9.configure(width=215)

        self.TFrame14 = ttk.Frame(self.TFrame4)
        self.TFrame14.place(relx=0.242, rely=0.063, relheight=0.906
                , relwidth=0.16)
        self.TFrame14.configure(relief='groove')
        self.TFrame14.configure(borderwidth="2")
        self.TFrame14.configure(relief='groove')
        self.TFrame14.configure(width=205)

        self.TLabel5 = ttk.Label(self.TFrame4)
        self.TLabel5.place(relx=0.476, rely=0.063, height=24, width=95)
        self.TLabel5.configure(background="#d9d9d9")
        self.TLabel5.configure(foreground="#000000")
        self.TLabel5.configure(font=font9)
        self.TLabel5.configure(relief='flat')
        self.TLabel5.configure(text='''Diagrammen''')

        self.TLabel12 = ttk.Label(self.TFrame4)
        self.TLabel12.place(relx=0.431, rely=0.188, height=24, width=81)
        self.TLabel12.configure(background="#d9d9d9")
        self.TLabel12.configure(foreground="#000000")
        self.TLabel12.configure(font="TkDefaultFont")
        self.TLabel12.configure(relief='flat')
        self.TLabel12.configure(text='''Tempratuur''')

        self.TLabel13 = ttk.Label(self.TFrame4)
        self.TLabel13.place(relx=0.543, rely=0.188, height=24, width=35)
        self.TLabel13.configure(background="#d9d9d9")
        self.TLabel13.configure(foreground="#000000")
        self.TLabel13.configure(font="TkDefaultFont")
        self.TLabel13.configure(relief='flat')
        self.TLabel13.configure(text='''Licht''')

        self.TButton9 = ttk.Button(self.TFrame4)
        self.TButton9.place(relx=0.424, rely=0.375, height=30, width=98)
        self.TButton9.configure(takefocus="")
        self.TButton9.configure(text='''Lijndiagram''')

        self.TButton10 = ttk.Button(self.TFrame4)
        self.TButton10.place(relx=0.424, rely=0.688, height=30, width=100)
        self.TButton10.configure(takefocus="")
        self.TButton10.configure(text='''Staafdiagram''')

        self.TButton11 = ttk.Button(self.TFrame4)
        self.TButton11.place(relx=0.52, rely=0.375, height=30, width=98)
        self.TButton11.configure(takefocus="")
        self.TButton11.configure(text='''Lijndiagram''')

        self.TButton12 = ttk.Button(self.TFrame4)
        self.TButton12.place(relx=0.52, rely=0.688, height=30, width=100)
        self.TButton12.configure(takefocus="")
        self.TButton12.configure(text='''Staafdiagram''')

        self.TLabel20 = ttk.Label(self.TFrame4)
        self.TLabel20.place(relx=0.669, rely=0.063, height=24, width=90)
        self.TLabel20.configure(background="#d9d9d9")
        self.TLabel20.configure(foreground="#000000")
        self.TLabel20.configure(font=font9)
        self.TLabel20.configure(relief='flat')
        self.TLabel20.configure(text='''Op/uitrollen''')

        self.TButton23 = ttk.Button(self.TFrame4)
        self.TButton23.place(relx=0.974, rely=0.0, height=30, width=38)
        self.TButton23.configure(takefocus="")
        self.TButton23.configure(text='''X''')

        self.TButton30 = ttk.Button(self.TFrame4)
        self.TButton30.place(relx=0.948, rely=0.0, height=30, width=38)
        self.TButton30.configure(takefocus="")
        self.TButton30.configure(text='''V''')

        self.TLabel42 = ttk.Label(self.TFrame4)
        self.TLabel42.place(relx=0.84, rely=0.063, height=24, width=94)
        self.TLabel42.configure(background="#d9d9d9")
        self.TLabel42.configure(foreground="#000000")
        self.TLabel42.configure(font=font9)
        self.TLabel42.configure(relief='flat')
        self.TLabel42.configure(takefocus="0")
        self.TLabel42.configure(text='''Automatisch''')

        self.TLabel43 = ttk.Label(self.TFrame4)
        self.TLabel43.place(relx=0.639, rely=0.375, height=24, width=67)
        self.TLabel43.configure(background="#d9d9d9")
        self.TLabel43.configure(foreground="#000000")
        self.TLabel43.configure(font="TkDefaultFont")
        self.TLabel43.configure(relief='flat')
        self.TLabel43.configure(wraplength="0")
        self.TLabel43.configure(takefocus="0")
        self.TLabel43.configure(text='''Rolstand:''')
        self.TLabel43.configure(width=0)

        self.TLabel45 = ttk.Label(self.TFrame4)
        self.TLabel45.place(relx=0.81, rely=0.375, height=24, width=45)
        self.TLabel45.configure(background="#d9d9d9")
        self.TLabel45.configure(foreground="#000000")
        self.TLabel45.configure(font="TkDefaultFont")
        self.TLabel45.configure(relief='flat')
        self.TLabel45.configure(takefocus="0")
        self.TLabel45.configure(text='''Temp:''')

        self.TLabel46 = ttk.Label(self.TFrame4)
        self.TLabel46.place(relx=0.87, rely=0.375, height=24, width=38)
        self.TLabel46.configure(background="#d9d9d9")
        self.TLabel46.configure(foreground="#000000")
        self.TLabel46.configure(font="TkDefaultFont")
        self.TLabel46.configure(relief='flat')
        self.TLabel46.configure(takefocus="0")
        self.TLabel46.configure(text='''Licht:''')

        self.Scale7 = tk.Scale(self.TFrame4)
        self.Scale7.place(relx=0.684, rely=0.25, relwidth=0.074, relheight=0.0
                , height=47, bordermode='ignore')
        self.Scale7.configure(activebackground="#ececec")
        self.Scale7.configure(background="#d9d9d9")
        self.Scale7.configure(font="TkTextFont")
        self.Scale7.configure(foreground="#000000")
        self.Scale7.configure(highlightbackground="#d9d9d9")
        self.Scale7.configure(highlightcolor="black")
        self.Scale7.configure(orient="horizontal")
        self.Scale7.configure(takefocus="0")
        self.Scale7.configure(troughcolor="#d9d9d9")

        self.Entry9 = tk.Entry(self.TFrame4)
        self.Entry9.place(relx=0.84, rely=0.375,height=24, relwidth=0.019)
        self.Entry9.configure(background="white")
        self.Entry9.configure(disabledforeground="#a3a3a3")
        self.Entry9.configure(font="TkFixedFont")
        self.Entry9.configure(foreground="#000000")
        self.Entry9.configure(highlightbackground="#d9d9d9")
        self.Entry9.configure(highlightcolor="black")
        self.Entry9.configure(insertbackground="black")
        self.Entry9.configure(selectbackground="#c4c4c4")
        self.Entry9.configure(selectforeground="black")
        self.Entry9.configure(takefocus="0")

        self.Entry10 = tk.Entry(self.TFrame4)
        self.Entry10.place(relx=0.892, rely=0.375,height=24, relwidth=0.019)
        self.Entry10.configure(background="white")
        self.Entry10.configure(disabledforeground="#a3a3a3")
        self.Entry10.configure(font="TkFixedFont")
        self.Entry10.configure(foreground="#000000")
        self.Entry10.configure(highlightbackground="#d9d9d9")
        self.Entry10.configure(highlightcolor="black")
        self.Entry10.configure(insertbackground="black")
        self.Entry10.configure(selectbackground="#c4c4c4")
        self.Entry10.configure(selectforeground="black")
        self.Entry10.configure(takefocus="0")

        self.TButton39 = ttk.Button(self.TFrame4)
        self.TButton39.place(relx=0.669, rely=0.688, height=30, width=98)
        self.TButton39.configure(takefocus="")
        self.TButton39.configure(text='''Submit''')

        self.TButton40 = ttk.Button(self.TFrame4)
        self.TButton40.place(relx=0.84, rely=0.688, height=30, width=98)
        self.TButton40.configure(takefocus="")
        self.TButton40.configure(text='''Submit''')

        self.TFrame5 = ttk.Frame(top)
        self.TFrame5.place(relx=0.0, rely=0.598, relheight=0.19, relwidth=0.991)
        self.TFrame5.configure(relief='groove')
        self.TFrame5.configure(borderwidth="2")
        self.TFrame5.configure(relief='groove')
        self.TFrame5.configure(width=1325)

        self.TFrame10 = ttk.Frame(self.TFrame5)
        self.TFrame10.place(relx=0.004, rely=0.063, relheight=0.906
                , relwidth=0.227)
        self.TFrame10.configure(relief='groove')
        self.TFrame10.configure(borderwidth="2")
        self.TFrame10.configure(relief='groove')
        self.TFrame10.configure(width=215)

        self.TFrame15 = ttk.Frame(self.TFrame5)
        self.TFrame15.place(relx=0.242, rely=0.063, relheight=0.906
                , relwidth=0.16)
        self.TFrame15.configure(relief='groove')
        self.TFrame15.configure(borderwidth="2")
        self.TFrame15.configure(relief='groove')
        self.TFrame15.configure(width=205)

        self.TLabel6 = ttk.Label(self.TFrame5)
        self.TLabel6.place(relx=0.476, rely=0.063, height=24, width=95)
        self.TLabel6.configure(background="#d9d9d9")
        self.TLabel6.configure(foreground="#000000")
        self.TLabel6.configure(font=font9)
        self.TLabel6.configure(relief='flat')
        self.TLabel6.configure(text='''Diagrammen''')

        self.TLabel14 = ttk.Label(self.TFrame5)
        self.TLabel14.place(relx=0.431, rely=0.188, height=24, width=81)
        self.TLabel14.configure(background="#d9d9d9")
        self.TLabel14.configure(foreground="#000000")
        self.TLabel14.configure(font="TkDefaultFont")
        self.TLabel14.configure(relief='flat')
        self.TLabel14.configure(text='''Tempratuur''')

        self.TLabel15 = ttk.Label(self.TFrame5)
        self.TLabel15.place(relx=0.543, rely=0.188, height=24, width=35)
        self.TLabel15.configure(background="#d9d9d9")
        self.TLabel15.configure(foreground="#000000")
        self.TLabel15.configure(font="TkDefaultFont")
        self.TLabel15.configure(relief='flat')
        self.TLabel15.configure(text='''Licht''')

        self.TButton13 = ttk.Button(self.TFrame5)
        self.TButton13.place(relx=0.424, rely=0.375, height=30, width=98)
        self.TButton13.configure(takefocus="")
        self.TButton13.configure(text='''Lijndiagram''')

        self.TButton14 = ttk.Button(self.TFrame5)
        self.TButton14.place(relx=0.424, rely=0.688, height=30, width=100)
        self.TButton14.configure(takefocus="")
        self.TButton14.configure(text='''Staafdiagram''')

        self.TButton15 = ttk.Button(self.TFrame5)
        self.TButton15.place(relx=0.52, rely=0.375, height=30, width=98)
        self.TButton15.configure(takefocus="")
        self.TButton15.configure(text='''Lijndiagram''')

        self.TButton16 = ttk.Button(self.TFrame5)
        self.TButton16.place(relx=0.52, rely=0.688, height=30, width=100)
        self.TButton16.configure(takefocus="")
        self.TButton16.configure(text='''Staafdiagram''')

        self.TLabel21 = ttk.Label(self.TFrame5)
        self.TLabel21.place(relx=0.669, rely=0.063, height=24, width=90)
        self.TLabel21.configure(background="#d9d9d9")
        self.TLabel21.configure(foreground="#000000")
        self.TLabel21.configure(font=font9)
        self.TLabel21.configure(relief='flat')
        self.TLabel21.configure(text='''Op/uitrollen''')

        self.TButton24 = ttk.Button(self.TFrame5)
        self.TButton24.place(relx=0.974, rely=0.0, height=30, width=38)
        self.TButton24.configure(takefocus="")
        self.TButton24.configure(text='''X''')

        self.TButton31 = ttk.Button(self.TFrame5)
        self.TButton31.place(relx=0.948, rely=0.0, height=30, width=38)
        self.TButton31.configure(takefocus="")
        self.TButton31.configure(text='''V''')

        self.TLabel37 = ttk.Label(self.TFrame5)
        self.TLabel37.place(relx=0.84, rely=0.063, height=24, width=94)
        self.TLabel37.configure(background="#d9d9d9")
        self.TLabel37.configure(foreground="#000000")
        self.TLabel37.configure(font=font9)
        self.TLabel37.configure(relief='flat')
        self.TLabel37.configure(takefocus="0")
        self.TLabel37.configure(text='''Automatisch''')

        self.TLabel38 = ttk.Label(self.TFrame5)
        self.TLabel38.place(relx=0.639, rely=0.375, height=24, width=67)
        self.TLabel38.configure(background="#d9d9d9")
        self.TLabel38.configure(foreground="#000000")
        self.TLabel38.configure(font="TkDefaultFont")
        self.TLabel38.configure(relief='flat')
        self.TLabel38.configure(wraplength="0")
        self.TLabel38.configure(takefocus="0")
        self.TLabel38.configure(text='''Rolstand:''')
        self.TLabel38.configure(width=0)

        self.TLabel40 = ttk.Label(self.TFrame5)
        self.TLabel40.place(relx=0.81, rely=0.375, height=24, width=45)
        self.TLabel40.configure(background="#d9d9d9")
        self.TLabel40.configure(foreground="#000000")
        self.TLabel40.configure(font="TkDefaultFont")
        self.TLabel40.configure(relief='flat')
        self.TLabel40.configure(takefocus="0")
        self.TLabel40.configure(text='''Temp:''')

        self.TLabel41 = ttk.Label(self.TFrame5)
        self.TLabel41.place(relx=0.87, rely=0.375, height=24, width=38)
        self.TLabel41.configure(background="#d9d9d9")
        self.TLabel41.configure(foreground="#000000")
        self.TLabel41.configure(font="TkDefaultFont")
        self.TLabel41.configure(relief='flat')
        self.TLabel41.configure(takefocus="0")
        self.TLabel41.configure(text='''Licht:''')

        self.Scale6 = tk.Scale(self.TFrame5)
        self.Scale6.place(relx=0.684, rely=0.25, relwidth=0.074, relheight=0.0
                , height=47, bordermode='ignore')
        self.Scale6.configure(activebackground="#ececec")
        self.Scale6.configure(background="#d9d9d9")
        self.Scale6.configure(font="TkTextFont")
        self.Scale6.configure(foreground="#000000")
        self.Scale6.configure(highlightbackground="#d9d9d9")
        self.Scale6.configure(highlightcolor="black")
        self.Scale6.configure(orient="horizontal")
        self.Scale6.configure(takefocus="0")
        self.Scale6.configure(troughcolor="#d9d9d9")

        self.Entry7 = tk.Entry(self.TFrame5)
        self.Entry7.place(relx=0.84, rely=0.375,height=24, relwidth=0.019)
        self.Entry7.configure(background="white")
        self.Entry7.configure(disabledforeground="#a3a3a3")
        self.Entry7.configure(font="TkFixedFont")
        self.Entry7.configure(foreground="#000000")
        self.Entry7.configure(highlightbackground="#d9d9d9")
        self.Entry7.configure(highlightcolor="black")
        self.Entry7.configure(insertbackground="black")
        self.Entry7.configure(selectbackground="#c4c4c4")
        self.Entry7.configure(selectforeground="black")
        self.Entry7.configure(takefocus="0")

        self.Entry8 = tk.Entry(self.TFrame5)
        self.Entry8.place(relx=0.892, rely=0.375,height=24, relwidth=0.019)
        self.Entry8.configure(background="white")
        self.Entry8.configure(disabledforeground="#a3a3a3")
        self.Entry8.configure(font="TkFixedFont")
        self.Entry8.configure(foreground="#000000")
        self.Entry8.configure(highlightbackground="#d9d9d9")
        self.Entry8.configure(highlightcolor="black")
        self.Entry8.configure(insertbackground="black")
        self.Entry8.configure(selectbackground="#c4c4c4")
        self.Entry8.configure(selectforeground="black")
        self.Entry8.configure(takefocus="0")

        self.TButton37 = ttk.Button(self.TFrame5)
        self.TButton37.place(relx=0.669, rely=0.688, height=30, width=98)
        self.TButton37.configure(takefocus="")
        self.TButton37.configure(text='''Submit''')

        self.TButton38 = ttk.Button(self.TFrame5)
        self.TButton38.place(relx=0.84, rely=0.688, height=30, width=98)
        self.TButton38.configure(takefocus="")
        self.TButton38.configure(text='''Submit''')

        self.TFrame6 = ttk.Frame(top)
        self.TFrame6.place(relx=0.0, rely=0.415, relheight=0.19, relwidth=0.991)
        self.TFrame6.configure(relief='groove')
        self.TFrame6.configure(borderwidth="2")
        self.TFrame6.configure(relief='groove')
        self.TFrame6.configure(width=1325)

        self.TFrame11 = ttk.Frame(self.TFrame6)
        self.TFrame11.place(relx=0.004, rely=0.031, relheight=0.906
                , relwidth=0.227)
        self.TFrame11.configure(relief='groove')
        self.TFrame11.configure(borderwidth="2")
        self.TFrame11.configure(relief='groove')
        self.TFrame11.configure(width=215)

        self.TFrame16 = ttk.Frame(self.TFrame6)
        self.TFrame16.place(relx=0.242, rely=0.031, relheight=0.906
                , relwidth=0.16)
        self.TFrame16.configure(relief='groove')
        self.TFrame16.configure(borderwidth="2")
        self.TFrame16.configure(relief='groove')
        self.TFrame16.configure(width=205)

        self.TLabel7 = ttk.Label(self.TFrame6)
        self.TLabel7.place(relx=0.476, rely=0.063, height=24, width=95)
        self.TLabel7.configure(background="#d9d9d9")
        self.TLabel7.configure(foreground="#000000")
        self.TLabel7.configure(font=font9)
        self.TLabel7.configure(relief='flat')
        self.TLabel7.configure(text='''Diagrammen''')

        self.TLabel16 = ttk.Label(self.TFrame6)
        self.TLabel16.place(relx=0.431, rely=0.188, height=24, width=81)
        self.TLabel16.configure(background="#d9d9d9")
        self.TLabel16.configure(foreground="#000000")
        self.TLabel16.configure(font="TkDefaultFont")
        self.TLabel16.configure(relief='flat')
        self.TLabel16.configure(text='''Tempratuur''')

        self.TLabel17 = ttk.Label(self.TFrame6)
        self.TLabel17.place(relx=0.543, rely=0.188, height=24, width=35)
        self.TLabel17.configure(background="#d9d9d9")
        self.TLabel17.configure(foreground="#000000")
        self.TLabel17.configure(font="TkDefaultFont")
        self.TLabel17.configure(relief='flat')
        self.TLabel17.configure(text='''Licht''')

        self.TButton17 = ttk.Button(self.TFrame6)
        self.TButton17.place(relx=0.424, rely=0.375, height=30, width=98)
        self.TButton17.configure(takefocus="")
        self.TButton17.configure(text='''Lijndiagram''')

        self.TButton18 = ttk.Button(self.TFrame6)
        self.TButton18.place(relx=0.424, rely=0.688, height=30, width=100)
        self.TButton18.configure(takefocus="")
        self.TButton18.configure(text='''Staafdiagram''')

        self.TButton19 = ttk.Button(self.TFrame6)
        self.TButton19.place(relx=0.52, rely=0.375, height=30, width=98)
        self.TButton19.configure(takefocus="")
        self.TButton19.configure(text='''Lijndiagram''')

        self.TButton20 = ttk.Button(self.TFrame6)
        self.TButton20.place(relx=0.52, rely=0.688, height=30, width=100)
        self.TButton20.configure(takefocus="")
        self.TButton20.configure(text='''Staafdiagram''')

        self.TLabel22 = ttk.Label(self.TFrame6)
        self.TLabel22.place(relx=0.669, rely=0.063, height=24, width=90)
        self.TLabel22.configure(background="#d9d9d9")
        self.TLabel22.configure(foreground="#000000")
        self.TLabel22.configure(font=font9)
        self.TLabel22.configure(relief='flat')
        self.TLabel22.configure(text='''Op/uitrollen''')

        self.TButton25 = ttk.Button(self.TFrame6)
        self.TButton25.place(relx=0.974, rely=0.0, height=30, width=38)
        self.TButton25.configure(takefocus="")
        self.TButton25.configure(text='''X''')

        self.TButton32 = ttk.Button(self.TFrame6)
        self.TButton32.place(relx=0.948, rely=0.0, height=30, width=38)
        self.TButton32.configure(takefocus="")
        self.TButton32.configure(text='''V''')

        self.TLabel32 = ttk.Label(self.TFrame6)
        self.TLabel32.place(relx=0.84, rely=0.063, height=24, width=94)
        self.TLabel32.configure(background="#d9d9d9")
        self.TLabel32.configure(foreground="#000000")
        self.TLabel32.configure(font=font9)
        self.TLabel32.configure(relief='flat')
        self.TLabel32.configure(takefocus="0")
        self.TLabel32.configure(text='''Automatisch''')

        self.TLabel33 = ttk.Label(self.TFrame6)
        self.TLabel33.place(relx=0.639, rely=0.375, height=24, width=67)
        self.TLabel33.configure(background="#d9d9d9")
        self.TLabel33.configure(foreground="#000000")
        self.TLabel33.configure(font="TkDefaultFont")
        self.TLabel33.configure(relief='flat')
        self.TLabel33.configure(wraplength="0")
        self.TLabel33.configure(takefocus="0")
        self.TLabel33.configure(text='''Rolstand:''')
        self.TLabel33.configure(width=0)

        self.TLabel35 = ttk.Label(self.TFrame6)
        self.TLabel35.place(relx=0.81, rely=0.375, height=24, width=45)
        self.TLabel35.configure(background="#d9d9d9")
        self.TLabel35.configure(foreground="#000000")
        self.TLabel35.configure(font="TkDefaultFont")
        self.TLabel35.configure(relief='flat')
        self.TLabel35.configure(takefocus="0")
        self.TLabel35.configure(text='''Temp:''')

        self.TLabel36 = ttk.Label(self.TFrame6)
        self.TLabel36.place(relx=0.87, rely=0.375, height=24, width=38)
        self.TLabel36.configure(background="#d9d9d9")
        self.TLabel36.configure(foreground="#000000")
        self.TLabel36.configure(font="TkDefaultFont")
        self.TLabel36.configure(relief='flat')
        self.TLabel36.configure(takefocus="0")
        self.TLabel36.configure(text='''Licht:''')

        self.Scale5 = tk.Scale(self.TFrame6)
        self.Scale5.place(relx=0.684, rely=0.25, relwidth=0.074, relheight=0.0
                , height=47, bordermode='ignore')
        self.Scale5.configure(activebackground="#ececec")
        self.Scale5.configure(background="#d9d9d9")
        self.Scale5.configure(font="TkTextFont")
        self.Scale5.configure(foreground="#000000")
        self.Scale5.configure(highlightbackground="#d9d9d9")
        self.Scale5.configure(highlightcolor="black")
        self.Scale5.configure(orient="horizontal")
        self.Scale5.configure(takefocus="0")
        self.Scale5.configure(troughcolor="#d9d9d9")

        self.Entry5 = tk.Entry(self.TFrame6)
        self.Entry5.place(relx=0.84, rely=0.375,height=24, relwidth=0.019)
        self.Entry5.configure(background="white")
        self.Entry5.configure(disabledforeground="#a3a3a3")
        self.Entry5.configure(font="TkFixedFont")
        self.Entry5.configure(foreground="#000000")
        self.Entry5.configure(highlightbackground="#d9d9d9")
        self.Entry5.configure(highlightcolor="black")
        self.Entry5.configure(insertbackground="black")
        self.Entry5.configure(selectbackground="#c4c4c4")
        self.Entry5.configure(selectforeground="black")
        self.Entry5.configure(takefocus="0")

        self.Entry6 = tk.Entry(self.TFrame6)
        self.Entry6.place(relx=0.892, rely=0.375,height=24, relwidth=0.019)
        self.Entry6.configure(background="white")
        self.Entry6.configure(disabledforeground="#a3a3a3")
        self.Entry6.configure(font="TkFixedFont")
        self.Entry6.configure(foreground="#000000")
        self.Entry6.configure(highlightbackground="#d9d9d9")
        self.Entry6.configure(highlightcolor="black")
        self.Entry6.configure(insertbackground="black")
        self.Entry6.configure(selectbackground="#c4c4c4")
        self.Entry6.configure(selectforeground="black")
        self.Entry6.configure(takefocus="0")

        self.TButton35 = ttk.Button(self.TFrame6)
        self.TButton35.place(relx=0.669, rely=0.688, height=30, width=98)
        self.TButton35.configure(takefocus="")
        self.TButton35.configure(text='''Submit''')

        self.TButton36 = ttk.Button(self.TFrame6)
        self.TButton36.place(relx=0.84, rely=0.688, height=30, width=98)
        self.TButton36.configure(takefocus="")
        self.TButton36.configure(text='''Submit''')

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

if __name__ == '__main__':
    vp_start_gui()





